[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
rpc_endpoints = { ethereum = "${RPC_URL}", base = "${BASE_RPC_URL}", arbitrum = "${ARBITRUM_RPC_URL}", polygon = "${POLYGON_RPC_URL}", optimism = "${OPTIMISM_RPC_URL}", bsc = "${BSC_RPC_URL}", avalanche = "${AVALANCHE_RPC_URL}" }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"