[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_endpoints = { mainnet = "${RPC_URL}", arbitrum = "${ARBITRUM_RPC_URL}" }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "preserve"
